# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

# Activates the use of Zephyr's API for sensors
CONFIG_SENSOR=y
CONFIG_I2C=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_BMI323=y
CONFIG_BMI323_BUS_I2C=y

CONFIG_APP_LOG_LEVEL_DBG=y
CONFIG_SENSOR_LOG_LEVEL_DBG=y
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_LOG_PROCESS_THREAD_SLEEP_MS=1
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=1024
CONFIG_LOG_BUFFER_SIZE=8192
CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_RTIO=y
CONFIG_SENSOR_ASYNC_API=y